{% set version = "0.2.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-scatterpie
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/scatterpie_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/scatterpie/scatterpie_{{ version }}.tar.gz
  sha256: 56f1dccf7980c901c8e76dbd29801894d2075268eac7d2a0ce3a3923f3282c18

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggforce
    - r-ggfun
    - r-ggplot2
    - r-rlang
    - r-tidyr
    - r-yulab.utils >=0.1.6
  run:
    - r-base
    - r-dplyr
    - r-ggforce
    - r-ggfun
    - r-ggplot2
    - r-rlang
    - r-tidyr
    - r-yulab.utils >=0.1.6

test:
  commands:
    - $R -e "library('scatterpie')"           # [not win]
    - "\"%R%\" -e \"library('scatterpie')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=scatterpie
  license: Artistic-2.0
  summary: Creates scatterpie plots, especially useful for plotting pies on a map.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
    - ryanraaum

# Package: scatterpie
# Title: Scatter Pie Plot
# Version: 0.1.2
# Authors@R: person("Guangchuang", "Yu", email = "guangchuangyu@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-6485-8781"))
# Description: Creates scatterpie plots, especially useful for plotting pies on a map.
# Depends: R (>= 3.4.0), ggplot2
# Imports: ggforce, rlang, rvcheck (>= 0.1.0), tidyr, utils
# Suggests: knitr, prettydoc, maps
# VignetteBuilder: knitr
# License: Artistic-2.0
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-07-17 05:15:46 UTC; guangchuangyu
# Author: Guangchuang Yu [aut, cre] (<https://orcid.org/0000-0002-6485-8781>)
# Maintainer: Guangchuang Yu <guangchuangyu@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-07-17 05:40:03 UTC
